### ISSUE TITLE
Add Chainer Docs to website?

### ISSUE THREAD

**Issue by jlewi** [kubeflow/chainer-operator#23]
Is chainer ready for use?

When it is we should add docs to kubeflow.org?

**Comment by everpeace** [comment]
> Is chainer ready for use?
I think so.  

> When it is we should add docs to kubeflow.org?

We will be ready to add docs to kubeflow.org once #5 fixed.

@jlewi But, I'm not familiar with release/continuous delivery flow for kubeflow docker images.   I'm very appreciated if you gave some advice or reference.

**Comment by everpeace** [comment]
I'm closing this because chainer document is now on kubeflow.org 😃 

/close
